pagopa/p4pa-io-notification

- helm/Chart.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
> fix: Name chart and wrong indentation

- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IOFeignRestClient.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnector.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnectorImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/KeysDTO.java
- src/test/java/it/gov/pagopa/payhub/ionotification/connector/IORestClientTest.java
- Added client API get service keys
- Unit Test
> chore: P4ADEV-430-add-client-api-get-tokens

- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IOFeignRestClient.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnector.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnectorImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/FiscalCodeDTO.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/ProfileResource.java
- src/test/java/it/gov/pagopa/payhub/ionotification/connector/IORestClientTest.java
- Added client API Get a User Profile using POST
- Unit Test
> chore: P4ADEV-431-add-client-api-user-profile

- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceImpl.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceTest.java
Fix searche for all services from IO
> fix: Search io services

- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnector.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnectorImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/payhub/ionotification/connector/IORestClientTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
Fix API getAllServices  to get all pagineted services
> fix: Fix getAllServices 

- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnectorImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/payhub/ionotification/event/producer/IONotificationProducerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceSearchServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
- Bug fix search io serrvices
- Fix unit test for coverage
> fix: Bug fix search io service

- openapi/p4pa-io-notification.openapi.yaml
- src/main/java/it/gov/pagopa/payhub/ionotification/constants/IONotificationConstants.java
- src/main/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/mapper/IOServiceMapper.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandler.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/custom/ServiceNotFoundException.java
- src/main/java/it/gov/pagopa/payhub/ionotification/model/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IOServiceRepository.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IOServiceRepositoryExtImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceImpl.java
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/mapper/IONotificationMapperTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/mapper/IOServiceMapperTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/IOServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
- Added API getService
- UnitTest
> feat: P4ADEV-476-add-api-get-service

- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IOFeignRestClient.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnector.java
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnectorImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/custom/DeleteServiceInvocationException.java
- src/test/java/it/gov/pagopa/payhub/ionotification/connector/IORestClientTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/event/producer/IONotificationProducerTest.java
API cliente for deleteService from IO
> chore: P4ADEV-632-add-api-client-delete-service-from-io

- openapi/p4pa-io-notification.openapi.yaml
- src/main/java/it/gov/pagopa/payhub/ionotification/connector/IORestConnectorImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/constants/IONotificationConstants.java
- src/main/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandler.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/custom/ServiceAlreadyDeletedException.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IOServiceRepository.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceImpl.java
- src/test/java/it/gov/pagopa/payhub/ionotification/connector/IORestClientTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/IOServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceTest.java
- Added API deleteService from IO
- Unit Test
> feat: P4ADEV-630-add-api-delete-service-from-io

- openapi/p4pa-io-notification.openapi.yaml
- src/main/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/mapper/IOServiceMapper.java
- src/main/java/it/gov/pagopa/payhub/ionotification/model/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IOServiceRepository.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceImpl.java
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/mapper/IOServiceMapperTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/IOServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOServiceCreationServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
- Fix API client createService
- Fix API getService
The path variables are Long
> fix: P4ADEV-647-fix-api-client-create-service-and-get-service

- openapi/p4pa-io-notification.openapi.yaml
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
> fix: Fix-path-create-service

- .devops/deploy-pipelines.yml
- postman/p4pa-io-notification-E2E.postman_collection.json
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/mapper/IOServiceMapper.java
- Test Postman
- Fix null pointer getService
> chore: P4ADEV-631-test-postman

- openapi/p4pa-io-notification.openapi.yaml
Fix payload for API createService
> fix: Fix Payload API createService

- postman/p4pa-io-notification-E2E.postman_collection.json
> chore: P4ADEV-461-test-postman

- openapi/p4pa-io-notification.openapi.yaml
- src/main/java/it/gov/pagopa/payhub/ionotification/config/JsonConfig.java
> chore: Add Json Config

- openapi/p4pa-io-notification.openapi.yaml
- postman/p4pa-io-notification-E2E.postman_collection.json
- src/main/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/model/IONotification.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IONotificationRepository.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/ioservice/IOManageServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceImpl.java
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/IOServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceTest.java
> feat: P4ADEV-683-create-delete-notification

- openapi/p4pa-io-notification.openapi.yaml
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceImpl.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
> fix: P4ADEV-899-fix-payload

- helm/values.yaml
- openapi/p4pa-io-notification.openapi.yaml
- postman/p4pa-io-notification-E2E.postman_collection.json
- src/main/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/mapper/IONotificationMapper.java
- src/main/java/it/gov/pagopa/payhub/ionotification/event/producer/IONotificationProducer.java
- src/main/java/it/gov/pagopa/payhub/ionotification/model/IONotification.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IONotificationRepository.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/DataCipherService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/utils/AESUtils.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/mapper/IONotificationMapperTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/DataCipherServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/AESUtilsTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
Encrypt the fiscalCode to meet GDPR criteria
> fix: P4ADEV-908-encrypt-fiscal-code

- .github/CODEOWNERS
> fix: Code owners

- .github/CODEOWNERS
- helm/values.yaml
- openapi/p4pa-io-notification.openapi.yaml
- postman/p4pa-io-notification-E2E.postman_collection.json
- src/main/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/dto/mapper/IONotificationMapper.java
- src/main/java/it/gov/pagopa/payhub/ionotification/event/producer/IONotificationProducer.java
- src/main/java/it/gov/pagopa/payhub/ionotification/model/IONotification.java
- src/main/java/it/gov/pagopa/payhub/ionotification/repository/IONotificationRepository.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/DataCipherService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/IOServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationService.java
- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceImpl.java
- src/main/java/it/gov/pagopa/payhub/ionotification/utils/AESUtils.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/payhub/ionotification/controller/IONotificationControllerImplTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/mapper/IONotificationMapperTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/DataCipherServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/AESUtilsTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/IOTestMapper.java
* P4ADEV-908-encrypt-fiscal-code
* P4ADEV-899-fix-payload
* P4ADEV-908-encrypt-fiscal-code
> fix: P4ADEV-908-encrypt-fiscal-code (#33)

- helm/values.yaml
Add new secret io-notification-data-cipher-encrypt-password
> fix: P4ADEV-926-fix-cipher-key

- .devops/deploy-pipelines.yml
- added task to send message on slack in case of failing step in pipeline
> chore: P4ADEV-902 added task send message on slack to pipeline

- .identity/00_data.tf
- .identity/03_github_environment.tf
- .identity/99_locals.tf
> fix: Terraform init

- .github/workflows/payments-flow-docker-snapshot.yml
- .github/workflows/payments-flow-release.yml
- .github/workflows/pr-title.yml
- Dockerfile
- docker-compose.yml
- gradle/wrapper/gradle-wrapper.properties
- run-docker-compose.sh
- improve docker image to speedup the build
- use gradle 8.10.2 to speed up 12%
- added locale Europe/Rome to dockerimage
- added release and snapshot action to github
- added docker compose
Allow to use locale directly configured into Image docker
> feat: Docker with localtime Europe/Rome and release actions

- .devops/deploy-pipelines.yml
> fix: Postman environment

- src/main/java/it/gov/pagopa/payhub/ionotification/service/notify/IONotificationServiceImpl.java
> fix: Fix notification message

- helm/values.yaml
- src/main/resources/application.yml
> fix: Fix env variable names

- .identity/00_data.tf
- .identity/03_github_environment.tf
- .identity/99_locals.tf
> feat: add sonar token & var

- build.gradle.kts
- openapi/p4pa-io-notification.openapi.yaml
- postman/p4pa-io-notification-E2E.postman_collection.json
- src/main/java/it/gov/pagopa/payhub/ionotification/config/json/JsonConfig.java
- src/main/java/it/gov/pagopa/payhub/ionotification/config/json/LocalDateTimeToOffsetDateTimeSerializer.java
- src/main/java/it/gov/pagopa/payhub/ionotification/config/json/OffsetDateTimeToLocalDateTimeDeserializer.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandler.java
- src/main/java/it/gov/pagopa/payhub/ionotification/exception/MongoTooManyRequestsExceptionHandler.java
- src/test/java/it/gov/pagopa/payhub/ionotification/config/json/LocalDateTimeToOffsetDateTimeSerializerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/config/json/OffsetDateTimeToLocalDateTimeDeserializerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/exception/IONotificationExceptionHandlerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/exception/MongoTooManyRequestsExceptionHandlerTest.java
> fix: Fix ErrorHandling and LocalDateTime json serialization

- .github/workflows/flow-docker-snapshot.yml
- .github/workflows/flow-release.yml
> chore: Trigger azure devops

- build.gradle.kts
- src/main/java/it/gov/pagopa/payhub/ionotification/performancelogger/ApiRequestPerformanceLogger.java
- src/main/java/it/gov/pagopa/payhub/ionotification/performancelogger/PerformanceLogger.java
- src/main/java/it/gov/pagopa/payhub/ionotification/performancelogger/PerformanceLoggerThresholdLevels.java
- src/main/java/it/gov/pagopa/payhub/ionotification/performancelogger/RestInvokePerformanceLogger.java
- src/main/resources/application.yml
- src/test/java/it/gov/pagopa/payhub/ionotification/performancelogger/ApiRequestPerformanceLoggerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/performancelogger/PerformanceLoggerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/performancelogger/RestInvokePerformanceLoggerTest.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/MemoryAppender.java
> feat: Performance logging

- src/main/java/it/gov/pagopa/payhub/ionotification/performancelogger/RestInvokePerformanceLogger.java
- src/main/java/it/gov/pagopa/payhub/ionotification/utils/SecurityUtils.java
- src/test/java/it/gov/pagopa/payhub/ionotification/utils/SecurityUtilsTest.java
> fix: PII in REST_INVOKE logs
